# write a simple TSPLIB format file from a dist object or
# a symmetric matrix containing the dissimilarities

TSPLIB_write <- function(dist, file, precision = 6) {
    
    # NAs are not possible
    if(any(is.na(dist))) stop("NAs cannot be handled")
   
    if(inherits(dist, "dist")) p <- attr(dist, "Size")
    else p <- ncol(dist)

    
    zz <- file(file, "w")

    cat("NAME: tsp",
        "COMMENT: generated by TSPLIB_write",
        "TYPE: TSP",
        paste("DIMENSION:", p),
        "EDGE_WEIGHT_TYPE: EXPLICIT",
        "EDGE_WEIGHT_FORMAT: FULL_MATRIX",
        file = zz, sep = "\n")
    

    # concorde cannot handle EDGE_WEIGHT_FORMAT: LOWER_COL yet!
    # infinity is not available
    inf_index <- is.infinite(dist)
    if(any(inf_index)) {
        dist[inf_index] <- max(dist[!inf_index]) * 2
    }
    # only integers can be used as weights in TSPLIB
    dist <- as.integer(as.matrix(dist) * 10^precision)

    cat("EDGE_WEIGHT_SECTION", dist, file = zz, sep = "\n")

    cat("EOF", file = zz, sep = "\n")

    close(zz)
}

