TSPLIB_write <- function(dist, file) {

    zz <- file(file, "w")

    cat("NAME: tsp",
        "COMMENT: generated by TSPLIB_write",
        "TYPE: TSP",
        paste("DIMENSION:", attr(dist, "Size")),
        "EDGE_WEIGHT_TYPE: EXPLICIT",
        "EDGE_WEIGHT_FORMAT: FULL_MATRIX",
        file = zz, sep = "\n")

    # concorde cannot handle EDGE_WEIGHT_FORMAT: LOWER_COL yet!
    # and only integers can be used as weights in TSPLIB
    MAX <- 1000000
    dist <- as.integer(as.matrix(dist) / max(dist) * MAX)

    cat("EDGE_WEIGHT_SECTION", dist, file = zz, sep = "\n")

    cat("EOF", file = zz, sep = "\n")

    close(zz)
}

