# write a simple TSPLIB format file from an object of class TSP
# (contains a dist object or a symmetric matrix) 

write_TSPLIB <- function(x, file, precision = 6) {
    
    if(!inherits(x, "TSP")) x <- TSP(x)
    # NAs are not possible
    if(any(is.na(x))) stop("NAs cannot be handled")
  
    if(inherits(x, "dist")){
        # Concorde can handle UPPER_ROW and dist (lower triangle matrix) 
        # is symmetric.
        format <- "EDGE_WEIGHT_FORMAT: UPPER_ROW"
    }else if(inherits(x, "matrix")){
        format <- "EDGE_WEIGHT_FORMAT: FULL_MATRIX"
    }else stop("unknown storage format")
    
    zz <- file(file, "w")

    cat("NAME: tsp",
        "COMMENT: generated by write_TSPLIB (R package tsp)",
        "TYPE: TSP",
        paste("DIMENSION:", cities(x)),
        "EDGE_WEIGHT_TYPE: EXPLICIT",
        format, 
        file = zz, sep = "\n")
    
    # fixes for TSPLIB/Concorde
    # infinity is not available so we use a relatively large number
    inf_index <- is.infinite(x)
    if(any(inf_index)) {
        x[inf_index] <- max(x[!inf_index]) * 2
    }
    
    # only integers can be used as weights
    if(storage.mode(x) != "integer") x <- as.integer(x * 10^precision)

    cat("EDGE_WEIGHT_SECTION", x, file = zz, sep = "\n")
    cat("EOF", file = zz, sep = "\n")

    close(zz)
}

