#######################################################################
# TSP - Traveling Salesperson Problem 
# Copyrigth (C) 2011 Michael Hahsler and Kurt Hornik
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


## generic
write_TSPLIB <- function(x, file, precision = 6, inf = NULL, neg_inf = NULL) 
  UseMethod("write_TSPLIB")


## write a simple TSPLIB format file from an object of class TSP
## (contains a dist object or a symmetric matrix) 

## TSP has data as integer
write_TSPLIB.TSP <- function(x, file, precision = 6, 
  inf = NULL, neg_inf = NULL) {
  
  if(is.null(inf)) inf <- .Machine$integer.max
  if(is.null(neg_inf)) neg_inf <- -inf
  
  ## Concorde can handle UPPER_ROW and dist (lower triangle matrix) 
  ## is symmetric.
  format <- "EDGE_WEIGHT_FORMAT: UPPER_ROW"
  
  zz <- file(file, "w")
  
  cat("NAME: TSP",
    "COMMENT: generated by write_TSPLIB (R-package TSP)",
    "TYPE: TSP",
    paste("DIMENSION:", n_of_cities(x)),
    "EDGE_WEIGHT_TYPE: EXPLICIT",
    format, 
    file = zz, sep = "\n")
  
  ## only integers can be used as weights
  if(storage.mode(x) != "integer") x <- x * 10^precision

  ## fix infinity values
  x[is.na(x)] <- inf
  x[x == Inf] <- inf
  x[x == -Inf] <- neg_inf  
  
  x <- suppressWarnings(as.integer(x))
  if(any(is.na(x))) stop("integer overflow, please reduce precision.")
  
  cat("EDGE_WEIGHT_SECTION", x, file = zz, sep = "\n")
  cat("EOF", file = zz, sep = "\n")
  
  close(zz)
}


write_TSPLIB.ATSP <- function(x, file, precision = 6, inf = NULL, neg_inf = NULL) {
  if(is.null(inf)) inf <- .Machine$integer.max
  if(is.null(neg_inf)) neg_inf <- -inf
  
  format <- "EDGE_WEIGHT_FORMAT: FULL_MATRIX"
  
  zz <- file(file, "w")
  
  cat("NAME: ATSP",
    "COMMENT: generated by write_TSPLIB (R package TSP)",
    "TYPE: ATSP",
    paste("DIMENSION:", n_of_cities(x)),
    "EDGE_WEIGHT_TYPE: EXPLICIT",
    format, 
    file = zz, sep = "\n")
  
  
  ## only integers can be used as weights
  if(storage.mode(x) != "integer") x <- x * 10^precision
  
  x[is.na(x)] <- Inf
  
  i <- which(is.infinite(x))
  if(length(i) > 0) { 
    if(is.null(inf)) {
      range_x <- range(x, na.rm = TRUE, finite = TRUE)
      inf <- range_x[2] + sum(range_x)
    }
    if(is.null(neg_inf)) neg_inf <- -inf
    
    x[i[x[i] == Inf]] <- inf
    x[i[x[i] == -Inf]] <- neg_inf
  }
  
  x <- suppressWarnings(as.integer(x))
  if(any(is.na(x))) stop("integer overflow, please reduce precision.")
  
  cat("EDGE_WEIGHT_SECTION", x, file = zz, sep = "\n")
  cat("EOF", file = zz, sep = "\n")
  
  close(zz)
}


## ETSP use data as real
write_TSPLIB.ETSP <- function(x, file, precision = 6, 
  inf = NULL, neg_inf = NULL) {
    
  if(ncol(x) == 2) type <- "EUC_2D"
  else if(ncol(x) == 3) type <- "EUC_3D"
  else stop("only EUC_2D and EUC_3D supported.")
  
  zz <- file(file, "w")
  
  cat("NAME: ETSP",
    "COMMENT: generated by write_TSPLIB (R package TSP)",
    "TYPE: TSP",
    paste("DIMENSION:", n_of_cities(x)),
    paste("EDGE_WEIGHT_TYPE:", type),
    file = zz, sep = "\n")
  
  
  ## fix NAs and Inf (punish Inf with max + 2*range) values
  x[is.na(x)] <- Inf

  i <- which(is.infinite(x))
  if(length(i) > 0) { 
    if(is.null(inf)) {
      range_x <- range(x, na.rm = TRUE, finite = TRUE)
      inf <- range_x[2] + sum(range_x)
    }
    if(is.null(neg_inf)) neg_inf <- -inf
      
    x[i[x[i] == Inf]] <- inf
    x[i[x[i] == -Inf]] <- neg_inf
  }
  
  
  ## fix row names
  rownames(x) <- NULL
  x <- do.call(data.frame, lapply(1:ncol(x), FUN = 
      function(i) sprintf(paste("%0.", precision, "e", sep=""), x[,i])))
  
  cat("NODE_COORD_SECTION", file = zz, sep = "\n")
  write.table(x, quote=FALSE, col.names = FALSE, file = zz) 
  cat("EOF", file = zz, sep = "\n")
  
  close(zz)
}


