## write a simple TSPLIB format file from an object of class TSP
## (contains a dist object or a symmetric matrix) 

write_TSPLIB.TSP <- function(x, file, precision = 6, inf = NULL) {
  
    ## Concorde can handle UPPER_ROW and dist (lower triangle matrix) 
    ## is symmetric.
    format <- "EDGE_WEIGHT_FORMAT: UPPER_ROW"
    
    zz <- file(file, "w")

    cat("NAME: tsp",
        "COMMENT: generated by write_TSPLIB (R package tsp)",
        "TYPE: TSP",
        paste("DIMENSION:", n_of_cities(x)),
        "EDGE_WEIGHT_TYPE: EXPLICIT",
        format, 
        file = zz, sep = "\n")
    
    ## fixes for TSPLIB/Concorde
    ## infinity is not available so we use a relatively large number
    posInf_index <- x == Inf
    if(any(posInf_index)) {
        posInf <- if(is.null(inf)) max(x[!posInf_index]) * 2 else inf
        warning(paste("Pos. infinity values are replaced by",
                posInf), immediate. = TRUE)
        x[posInf_index] <- posInf
    }
    
    negInf_index <- x == -Inf
    if(any(negInf_index)) {
        negInf <- if(is.null(inf)) min(x[!negInf_index]) * 2 else -inf
        warning(paste("Neg. infinity values are replaced by",
                negInf), immediate. = TRUE)
        x[negInf_index] <- negInf
    }
    
    ## only integers can be used as weights
    if(storage.mode(x) != "integer") x <- as.integer(x * 10^precision)

    cat("EDGE_WEIGHT_SECTION", x, file = zz, sep = "\n")
    cat("EOF", file = zz, sep = "\n")

    close(zz)
}

write_TSPLIB.ATSP <- function(x, file, precision = 6, inf = NULL) {
    format <- "EDGE_WEIGHT_FORMAT: FULL_MATRIX"
    
    zz <- file(file, "w")

    cat("NAME: tsp",
        "COMMENT: generated by write_TSPLIB (R package tsp)",
        "TYPE: ATSP",
        paste("DIMENSION:", n_of_cities(x)),
        "EDGE_WEIGHT_TYPE: EXPLICIT",
        format, 
        file = zz, sep = "\n")

    ## infinity is not available so we use a relatively large number
    posInf_index <- x == Inf
    if(any(posInf_index)) {
        posInf <- if(is.null(inf)) max(x[!posInf_index]) * 2 else inf
        warning(paste("Pos. infinity values are replaced by",
                posInf), immediate. = TRUE)
        x[posInf_index] <- negInf
    }

    negInf_index <- x == -Inf
    if(any(negInf_index)) {
        posInf <- if(is.null(inf)) min(x[!negInf_index]) * 2 else -inf
        warning(paste("Neg. infinity values are replaced by",
                negInf), immediate. = TRUE)
        x[negInf_index] <- negInf
    }
    
    ## only integers can be used as weights
    if(storage.mode(x) != "integer") x <- as.integer(x * 10^precision)

    cat("EDGE_WEIGHT_SECTION", x, file = zz, sep = "\n")
    cat("EOF", file = zz, sep = "\n")

    close(zz)
}

## generic
write_TSPLIB <- function(x, file, precision = 6, inf = NULL) 
    UseMethod("write_TSPLIB")

